require("mer.ashfall.camping.campfire.campfireInit")
require("mer.ashfall.camping.campfire.campfireLighting")
require("mer.ashfall.camping.campfire.campfireTooltip")
require("mer.ashfall.camping.campfire.campfireVisuals")
require("mer.ashfall.camping.campfire.campfireMenu")
require("mer.ashfall.camping.campfire.vanillaCampfireReplacer")

require("mer.ashfall.camping.brewerController")
require("mer.ashfall.camping.boilerController")
require("mer.ashfall.camping.cooking")
require("mer.ashfall.camping.firewood")
require("mer.ashfall.camping.fuelConsumerController")
require("mer.ashfall.camping.gearPlacement")
require("mer.ashfall.camping.grillDecals")
require("mer.ashfall.camping.harvestWood")
require("mer.ashfall.camping.stewerController")
