require("mer.ashfall.items.backpack")
require("mer.ashfall.items.bandages")
require("mer.ashfall.items.bedroll")
require("mer.ashfall.items.crabpot")
require("mer.ashfall.items.cooker")
require("mer.ashfall.items.cushion")
require("mer.ashfall.items.bugnet")
require("mer.ashfall.items.door")
require("mer.ashfall.items.dummy")
require("mer.ashfall.items.firewood")
require("mer.ashfall.items.teaWarmer")
require("mer.ashfall.items.waterFilter")

